/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353534",
        "outline": "#aa8986",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#e4e2e2",
        "on-secondary": "#303031",
        "on-surface": "#e5e2e1",
        "on-primary-container": "#5c0008",
        "shadow": "#000000",
        "secondary-fixed": "#e7c1bc",
        "on-secondary-fixed": "#2c1512",
        "on-surface-variant": "#d4c3c0",
        "scrim": "#000000",
        "primary-container": "#ba1224",
        "on-tertiary-container": "#200e19",
        "secondary": "#dfb9b4",
        "tertiary": "#dfbaba",
        "primary": "#ffb3b1",
        "on-background": "#e5e2e1",
        "inverse-primary": "#900010",
        "on-primary": "#550006",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "surface-container-low": "#1c1c1b",
        "surface-dim": "#131313",
        "on-secondary-container": "#5c1b17",
        "outline-variant": "#514341",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#410002",
        "error-container": "#93000a",
        "surface": "#131313",
        "error": "#ffb4ab",
        "surface-container": "#202020",
        "background": "#131313",
        "on-tertiary-fixed-variant": "#583f4f",
        "on-secondary-fixed-variant": "#5a403c",
        "surface-tint": "#ffb3b1",
        "surface-container-highest": "#353434",
        "inverse-on-surface": "#303031",
        "on-tertiary": "#140c11",
        "tertiary-container": "#694c5e",
        "on-tertiary-fixed": "#26131c",
        "secondary-container": "#762e26",
        "surface-bright": "#393939"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
